CREATE TABLE `producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) DEFAULT NULL, 
  `plu` VARCHAR(255) DEFAULT NULL, 
  `ean13` VARCHAR(255) DEFAULT NULL, 
  `precio1` VARCHAR(255) DEFAULT NULL, 
  `precio2` VARCHAR(255) DEFAULT NULL, 
  `precio3` VARCHAR(255) DEFAULT NULL, 
  `imagen` VARCHAR(255) DEFAULT NULL, 
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`)
);
